server:
  image: deviavir/zenbot:unstable
  volumes:
    - ./conf.js:/app/conf.js
    - ./extensions:/app/extensions
  links:
    - mongodb
  command: [ "trade", "--paper" ]
  restart: always

mongodb:
  image: mongo:latest
  volumes_from:
    - mongodb-data
  command: --bind_ip=localhost --logpath=/dev/null
  expose:
    - 27017
  
mongodb-data:
  image: mongo:latest
  volumes:
    - /data/db
  command: "true"